#show link: underline


== Những việc làm tốt
- Thực hiện nhiệm vụ được giao cho kịp tiến độ nhờ tận dụng hiệu quả AI.
- Khuyến khích cả nhóm trình bày minh chứng sử dụng AI.

== Những việc làm chưa tốt
- Vài thành viên còn cợt nhả trong quá trình thảo luận.
- Chưa thực sự tôn trọng nhóm trưởng.
- Cần khuyến khích cả nhóm tìm hiểu cách tạo, biên dịch và làm việc với Typst.
- Cần khuyến khích cả nhóm làm quen với bảng Kanban nằm trong GitHub Project của repo chứa tài liệu của cả nhóm.
    - #link("https://github.com/users/Huangphoux/projects/4")[
Liên kết đến GitHub Project của nhóm
]

== Đánh giá đóng góp từng thành viên

=== Hiệp
==== Phúc đánh giá rằng…
- Do để tiết kiệm thời gian nên nhóm trưởng (Trương Hoàng Phúc) đã tự thực hiện phần việc của bạn, thay vì giao cho bạn làm.
==== Huy đánh giá rằng…
==== Khang đánh giá rằng…
==== Hiệp đánh giá rằng…
==== Tùng đánh giá rằng…


=== Khang
==== Phúc đánh giá rằng…
- Thái độ chưa thực sự nghiêm túc.
==== Huy đánh giá rằng…
==== Khang đánh giá rằng…
==== Hiệp đánh giá rằng…
==== Tùng đánh giá rằng…

=== Huy
==== Phúc đánh giá rằng…
- Không có nhận xét cụ thể.
==== Huy đánh giá rằng…
==== Khang đánh giá rằng…
==== Hiệp đánh giá rằng…
==== Tùng đánh giá rằng…

=== Phúc
==== Phúc đánh giá rằng…
- Quả là một con người siêng năng, tuấn tú.
==== Huy đánh giá rằng…
==== Khang đánh giá rằng…
==== Hiệp đánh giá rằng…
==== Tùng đánh giá rằng…

=== Tùng
==== Phúc đánh giá rằng…
- Ít trao đổi, giao tiếp với cả nhóm.
- Quên nộp bài lên repo của nhóm.
==== Huy đánh giá rằng…
==== Khang đánh giá rằng…
==== Hiệp đánh giá rằng…
==== Tùng đánh giá rằng…

== Bài học rút ra
- Không có bài học rút ra cụ thể.

== Đề xuất cải thiện
- Hướng dẫn cả nhóm cách sử dụng Typst
- Hướng dẫn cả nhóm cách sử dụng GitHub Project
- Quản lí bài nộp tốt hơn
- Hướng dẫn các thành viên qui trình nộp bài